/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package homework04

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    ClassParser().parse()
}
