/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package homework04

class ClassParser {
    fun parse() = println("Parsed!")
}

fun main() {
  //  println(App().greeting)
}
