/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package homework03

import kotlinx.coroutines.runBlocking

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main(args: Array<String>) {
    println(App().greeting)
    runBlocking {
        val topic = RedditClient.getTopic("Kotlin")
        println(topic)
        val comments = RedditClient.getComments("z3qwxa/additional_monads_not_defined_in_arrow")
        println(comments)
        println(comments.linearize())
    }
}
